# Generated by Django 3.1.7 on 2021-03-19 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
