# Generated by Django 3.1.7 on 2021-03-19 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210319_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
