# Generated by Django 3.1.7 on 2021-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210319_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
