# Generated by Django 3.1.7 on 2021-03-22 11:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210322_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.FileField(default=1, upload_to=api.models.user_directory_path),
            preserve_default=False,
        ),
    ]
